### ISSUE TITLE
[Feature Request] Emit button for quick access from Emitter's header pane directly.

### ISSUE THREAD

**Issue by jpm8888** [firecamp-io/Firecamp#62]
firecamp version : 0.9.2

Could you please add Emit button in Socket.io

![Screenshot 2020-02-07 at 5 24 01 PM](https://user-images.githubusercontent.com/1531956/74027793-e5759380-49ce-11ea-8254-9c06d4a0c703.png)

right now it is too clumsy, it would be much faster to test sockets if you provide and emit button and i don't have to open the little editor and emit.

![Screenshot 2020-02-07 at 5 26 47 PM](https://user-images.githubusercontent.com/1531956/74027882-19e94f80-49cf-11ea-81ba-e6ecbea11884.png)

something like this.

![Screenshot 2020-02-07 at 5 24 01 PM](https://user-images.githubusercontent.com/1531956/74028104-9419d400-49cf-11ea-922f-33f6a5dfe503.png)

**Comment by Nishchit14** [comment]
That's a great idea,

I would like to discuss the points on that, Here in this case `CHOOSE_BET_AMOUNT` is an `emitter collection` which would have multiple bodies like 

- `CHOOSE_BET_AMOUNT`
   -- emitter-body-1
   -- emitter-body-2
   -- emitter-body-3

Once you click on the `CHOOSE_BET_AMOUNT`, the collection will get opened and you can see all the bodies in that with their payload. 

Right now you have only one body in every collection that's why it seems a bit heavy to go into it and click on the `emit` button. But when you have multiple bodies then you'll have to choose anyone from it. 

Now if we put the `emit` button directly on EMITERT COLLECTION then probably it would send/emit the first body saved into it. and to send/emit other than first emitter-body you have to click on collection name to open it.


would be happy to hear your thoughts @jpm8888

**Comment by jpm8888** [comment]
Generally speaking, 
If someone is testing in code sprint (which is most of the times.) they just send the same body until it works.

In this case we can also do one thing, we can enter values in environment and place them in emitter's body
```

{
    "bet_amount":{{amount}},
    "id" : {{id}}
}
```

**Comment by Nishchit14** [comment]
> If someone is testing in code sprint (which is most of the times.) they just send the same body until it works.

I agree with that... The purpose of the emitter collection is if one Emitter has multiple bodies then we can group them easily.

Like

Emitter `EVENT_JOIN_CHAT`

Body 1
```
{
   "name": "Bob",
   "type": "guest"
}
```

Body 2
```
{
   "name": "Alice",
   "type": "member"
}
```

>Note:
We're completely redesigning the SocketIO UI with lots of improvements and many new features like auto-connect, auto listens and event chaining. All the feedbacks/suggestions are most welcome 🙏

**Comment by hmenzagh** [comment]
The ability to change directly the JSON in the saved events would also be a life changer !
(+9000 on the simple emit button)

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
